// package gui implements the user interface of the project - template checker section
package gui

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/storage"
	"fyne.io/fyne/v2/widget"

	"github.com/artnikel/nuclei/internal/constants"
	"github.com/artnikel/nuclei/internal/logging"
	"github.com/artnikel/nuclei/internal/templates"
)

// BuildTemplateCheckerSection creates a UI section for checking and generating templates from URLs
func BuildTemplateCheckerSection(a fyne.App, parentWindow fyne.Window, logger *logging.Logger) fyne.CanvasObject {
	urlEntry := widget.NewEntry()
	urlEntry.SetPlaceHolder("Enter URL to check templates")

	templateCheckLabel := widget.NewLabel("Template folder: (not selected)")

	resultsOutput := widget.NewMultiLineEntry()
	resultsOutput.SetMinRowsVisible(10)
	resultsOutput.Wrapping = fyne.TextWrapWord

	createTemplateBtn := widget.NewButton("Create new template", nil)
	createTemplateBtn.Disable()

	var checkTemplatesDir string

	selectTemplateCheckDirBtn := widget.NewButton("Select templates folder for checking", func() {
		selectTemplatesFolder(parentWindow, &checkTemplatesDir, templateCheckLabel)
	})

	checkTemplatesBtn := widget.NewButton("Check templates", func() {
		checkTemplatesAction(parentWindow, urlEntry, checkTemplatesDir, resultsOutput, createTemplateBtn, logger)
	})

	createTemplateBtn.OnTapped = func() {
		createTemplateAction(parentWindow, urlEntry)
	}

	section := container.NewVBox(
		widget.NewLabel("Template Checker Section"),
		urlEntry,
		selectTemplateCheckDirBtn,
		templateCheckLabel,
		checkTemplatesBtn,
		resultsOutput,
		createTemplateBtn,
	)

	return section
}

// selectTemplatesFolder opens the dialog box for selecting a folder with templates and updates the path
func selectTemplatesFolder(parentWindow fyne.Window, dir *string, label *widget.Label) {
	fd := dialog.NewFolderOpen(func(uri fyne.ListableURI, err error) {
		if err != nil || uri == nil {
			return
		}
		*dir = uri.Path()
		label.SetText("Template folder: " + *dir)
	}, parentWindow)
	fd.Resize(fyne.NewSize(800, 600))
	fd.Show()
}

// checkTemplatesAction checks for matching templates for a given URL and updates the interface
func checkTemplatesAction(
	parentWindow fyne.Window,
	urlEntry *widget.Entry,
	templatesDir string,
	resultsOutput *widget.Entry,
	createBtn *widget.Button,
	logger *logging.Logger,
) {
	if templatesDir == "" {
		dialog.ShowInformation("Error", "Please select a templates folder", parentWindow)
		return
	}
	url := strings.TrimSpace(urlEntry.Text)
	if url == "" {
		dialog.ShowInformation("Error", "Please enter a URL", parentWindow)
		return
	}

	createBtn.Disable()
	resultsOutput.SetText("Starting template check...\n")

	go func() {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
		defer cancel()

		progressCallback := func(i, total int) {
			line := fmt.Sprintf("Checked %d of %d templates...", i, total)
			fyne.CurrentApp().Driver().DoFromGoroutine(func() {
				resultsOutput.SetText(line)
			}, true)
		}

		matched, err := templates.FindMatchingTemplates(ctx, url, templatesDir, constants.FiveSecTimeout, logger, progressCallback)
		if err != nil {
			fyne.CurrentApp().Driver().DoFromGoroutine(func() {
				dialog.ShowError(err, parentWindow)
			}, true)
			return
		}

		lines := []string{}

		fyne.CurrentApp().Driver().DoFromGoroutine(func() {
			if len(matched) == 0 {
				lines = append(lines, "No matching templates found.\nYou can create a new template.")
				resultsOutput.SetText(strings.Join(lines, "\n"))
				createBtn.Enable()
			} else {
				lines = append(lines, "\nTotal matching: "+strconv.Itoa(len(matched)))
				lines = append(lines, "\nMatching templates:")
				for _, tmpl := range matched {
					lines = append(lines, tmpl.ID)
				}
				resultsOutput.SetText(strings.Join(lines, "\n"))
			}
		}, true)
	}()
}

// createTemplateAction generates a template for the specified URL and offers to save it to a file
func createTemplateAction(parentWindow fyne.Window, urlEntry *widget.Entry) {
	url := strings.TrimSpace(urlEntry.Text)
	if url == "" {
		dialog.ShowInformation("Error", "Please enter a URL", parentWindow)
		return
	}

	tmpl := templates.GenerateTemplate(url)
	if strings.HasPrefix(tmpl, "# Failed") {
		dialog.ShowError(fmt.Errorf("template generation failed:\n%s", tmpl), parentWindow)
		return
	}

	saveDialog := dialog.NewFileSave(func(writer fyne.URIWriteCloser, err error) {
		if err != nil || writer == nil {
			return
		}
		_, err = writer.Write([]byte(tmpl))
		if err != nil {
			dialog.ShowError(err, parentWindow)
			return
		}
		writer.Close()
		dialog.ShowInformation("Success", "Template saved", parentWindow)
	}, parentWindow)
	saveDialog.SetFileName("autogenerated-template.yaml")
	saveDialog.SetFilter(storage.NewExtensionFileFilter([]string{constants.YamlFileFormat, constants.YmlFileFormat}))
	saveDialog.Show()
}
